version: '3.5'

services: 
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment: 
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks: 
            - default
            - alpine-net
    kafka:
        image: 'bitnami/kafka:latest'
        container_name: kafka
        ports:
            - "9092:9092"
        environment: 
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on: 
            - zookeeper
        networks: 
            - default
            - alpine-net
    fileserver:
        image: emazzotta/simple-fileserver-docker
        container_name: fileserver
        working_dir: /app
        volumes: 
            - /home/pertinate/fileserver:/app
        ports: 
            - 8000:8000
        network_mode: host
    server:
        image: node:14.13.1-alpine3.12
        container_name: server
        command: npm run dev
        build: .
        working_dir: /home/node/app
        volumes: 
            - $PWD:/home/node/app
        ports:
            - "8081:8081"
        expose: 
            - "9092"
        environment: 
            - "PORT=8081"
        depends_on: 
            - zookeeper
            - kafka
        network_mode: host
networks: 
    alpine-net:
        external: true
        name: alpine-net
        driver: bridge
