version: '3.5'

services:
    redis:
        image: "redis:alpine"
        container_name: redis
        command: redis-server --requirepass mypass
        environment: 
            - REDIS_REPLICATION_MODE=master
        network_mode: host
        ports: 
            - "6379:6379"
    fileserver:
        image: emazzotta/simple-fileserver-docker
        container_name: fileserver
        working_dir: /app
        volumes: 
            - /home/pertinate/fileserver:/app
        ports: 
            - 8000:8000
        network_mode: host
    server:
        image: node:14.13.1-alpine3.12
        container_name: server
        command: npm run dev
        build: .
        working_dir: /home/node/app
        volumes: 
            - $PWD:/home/node/app
        ports:
            - "8081:8081"
        expose: 
            - "9092"
        environment: 
            - "PORT=8081"
        depends_on: 
            - redis
            - fileserver
        network_mode: host
networks: 
    alpine-net:
        external: true
        name: alpine-net
        driver: bridge
